channels:
- defaults
- anaconda
- conda-forge
dependencies:
- python=3.6
- pip
- notebook
- ipykernel
- pip:
  - interpret
  - matplotlib
  - azureml-defaults==1.19.0
  - azureml-core==1.19.0
  - azureml-widgets==1.19.0
name: azureml_181610e2763c3ae45d46eb2c0b7a7a6f
