# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ actions-dev ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ actions-dev ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: az account show -o table
      - name: AzureML CLI Extension
        run: az extension add -n azure-cli-ml
      - name: Attach AzureML Workspace
        run: az ml folder attach -w azureml -g azureml
      - name: Model Training
        run: az ml run submit-script -c diabetes -e titanic-exp  --path $GITHUB_WORKSPACE --source-directory $GITHUB_WORKSPACE/train -t runoutput.json train-diabetes.py
      - name: Model Registry
        run: az ml model register -n diabetes-model -f runoutput.json --asset-path "outputs/diabetes-model.pkl" -t registeredmodel.json
      - name: Deploy to ACI
        run: az ml model deploy -n diabetes -f registeredmodel.json --ic $GITHUB_WORKSPACE/deploy/inferenceConfig.json --dc $GITHUB_WORKSPACE/deploy/aciDeploymentConfig.yml -e diabetes-env
