name: MLOps CICD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az account show -o table
      - name: AzureML CLI Extension
        run: az extension add -n azure-cli-ml
      - name: Attach AzureML Workspace
        run: az ml folder attach -w azureml -g azureml
      - name: Model Training
        run: az ml run submit-script -c diabetes -e titanic-exp  --source-directory train -t runoutput.json train-diabetes.py
      - name: Model Registry
        run: az ml model register -n diabetes-model -f runoutput.json --asset-path "outputs/diabetes-model.pkl" -t registeredmodel.json
      - name: Store Metadata
        uses: actions/upload-artifact@v2
        with:
          name: metadata-train
          path: registeredmodel.json
  staging:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript: az account show -o table
      - name: Download Metadata (From Training)
        uses: actions/download-artifact@v2
        with:
          name: metadata-train
          path: .
      - name: AzureML CLI Extension
        run: az extension add -n azure-cli-ml
      - name: Deploy to ACI
        run: az ml model deploy -n diabetes -f registeredmodel.json --ic $GITHUB_WORKSPACE/deploy/inferenceConfig.json --dc $GITHUB_WORKSPACE/deploy/aciDeploymentConfig.yml -e diabetes-env --overwrite
